apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  type: LoadBalancer
  selector:
    app: java
  ports:  
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30009
