apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  # Encoded value of password: echo -n "c2VjcmV0" | base64 -d   (secret)
  # Encoded value of username: echo -n "cm9vdA==" | base64 -d   (root)
  mariadb-root-password: c2VjcmV0      
  username: cm9vdA==   




